language: node_js
node_js:
  - "6"

before_script:
  - npm install -g yarn
  - yarn install

scripts:
  - yarn build

deploy:
  - provider: script
      script: yarn deploy
      on:
        branch: stable
